services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Senha@123456"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver-data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

  users-api:
    build:
      context: ../UsersAPI

    container_name: users-api

    ports:
      - "5001:8080"

    depends_on:
      - sqlserver
      - rabbitmq

    environment:
      ConnectionStrings__Database: Server=sqlserver,1433;Database=UsersDb;User Id=sa;Password=Senha@123456;TrustServerCertificate=True
      RABBITMQ_HOST: rabbitmq

  catalog-api:
    build:
      context: ../CatalogAPI

    container_name: catalog-api

    ports:
      - "5002:8080"

    depends_on:
      - sqlserver
      - rabbitmq

    environment:
      ConnectionStrings__Database: Server=sqlserver,1433;Database=CatalogDb;User Id=sa;Password=Senha@123456;TrustServerCertificate=True
      RABBITMQ_HOST: rabbitmq

  payments-api:
    build:
      context: ../PaymentsAPI

    container_name: payments-api

    ports:
      - "5003:8080"

    depends_on:
      - sqlserver
      - rabbitmq

    environment:
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=PaymentsDb;User Id=sa;Password=Senha@123456;TrustServerCertificate=True
      RABBITMQ_HOST: rabbitmq

  notifications-api:
    build:
      context: ../NotificationsAPI

    container_name: notifications-api

    ports:
      - "5004:8080"

    depends_on:
      - rabbitmq

    environment:
      RABBITMQ_HOST: rabbitmq

volumes:
  sqlserver-data: