apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secret
type: Opaque
stringData:
  CONNECTION_STRING: "Server=sqlserver,1433;Database=PaymentsDb;User Id=sa;Password=Senha@123456;TrustServerCertificate=True"