apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
type: Opaque
stringData:
  CONNECTION_STRING: "Server=sqlserver,1433;Database=UsersDb;User Id=sa;Password=Senha@123456;TrustServerCertificate=True"

  JWT_SECRET: "MinhaChaveSuperSecretaComMaisDe32Caracteres123"